### ISSUE TITLE
Configure Teensy to run interrupt routine from a GPIO pin

### ISSUE THREAD

**Issue by nicbres** [vortexntnu/Teensy#5]
*Description*: Use a GPIO pin (on a different port than the ADC data lines) to trigger an interrupt that will eventually call the read data function.
*Goal*:
- familiarize with Teensy interrupts and interrupt table
- configuring microcontroller manually with registers
- functioning interrupt on the GPIO

**Comment by Crezle** [comment]
Commit 094ec185c84eb62f0a9d65a82134e9899c8cd00b fixed this issue
